# Generated by Django 4.1.7 on 2023-05-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_products_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motagrat_products',
            name='buy_price',
        ),
    ]
