# Generated by Django 4.1.7 on 2023-05-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_motagrat_products_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motagrat_products',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='motagrat_products',
            name='buy_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
